# Generated by Django 2.2.6 on 2021-12-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='username',
        ),
    ]
