# Generated by Django 2.2.6 on 2021-12-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0011_remove_reader_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reader',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
